version: '3.9'

services:
  postgres:
    container_name: postgres15
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-qwe123}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwe123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}  # Default database to connect to initially
    ports:
      - '5432:5432'
    restart: always

  redis:
    container_name: redis6
    image: redis:6
    ports:
      - '6379:6379'
    environment:
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY:-2GB}
    restart: always
