# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc_api.proto\x12\x0e\x65vent_provider\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x0c\n\x04odds\x18\x03 \x01(\x01\x12+\n\x06status\x18\x04 \x01(\x0e\x32\x1b.event_provider.EventStatus\x12-\n\tfinish_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"e\n\x12\x43reateEventRequest\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0c\n\x04odds\x18\x02 \x01(\x01\x12-\n\tfinish_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x13\x43reateEventResponse\x12$\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x15.event_provider.Event\">\n\x0fGetEventRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x14\n\nevent_name\x18\x02 \x01(\tH\x00\x42\x07\n\x05query\"8\n\x10GetEventResponse\x12$\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x15.event_provider.Event\"\x16\n\x14GetListEventsRequest\">\n\x15GetListEventsResponse\x12%\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x15.event_provider.Event\"S\n\x18UpdateEventStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.event_provider.EventStatus*;\n\x0b\x45ventStatus\x12\x0e\n\nUNFINISHED\x10\x00\x12\r\n\tTEAM1_WON\x10\x01\x12\r\n\tTEAM2_WON\x10\x02\x32\xee\x02\n\x13LineProviderService\x12V\n\x0b\x43reateEvent\x12\".event_provider.CreateEventRequest\x1a#.event_provider.CreateEventResponse\x12M\n\x08GetEvent\x12\x1f.event_provider.GetEventRequest\x1a .event_provider.GetEventResponse\x12Y\n\nListEvents\x12$.event_provider.GetListEventsRequest\x1a%.event_provider.GetListEventsResponse\x12U\n\x11UpdateEventStatus\x12(.event_provider.UpdateEventStatusRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSTATUS']._serialized_start=799
  _globals['_EVENTSTATUS']._serialized_end=858
  _globals['_EVENT']._serialized_start=97
  _globals['_EVENT']._serialized_end=338
  _globals['_CREATEEVENTREQUEST']._serialized_start=340
  _globals['_CREATEEVENTREQUEST']._serialized_end=441
  _globals['_CREATEEVENTRESPONSE']._serialized_start=443
  _globals['_CREATEEVENTRESPONSE']._serialized_end=502
  _globals['_GETEVENTREQUEST']._serialized_start=504
  _globals['_GETEVENTREQUEST']._serialized_end=566
  _globals['_GETEVENTRESPONSE']._serialized_start=568
  _globals['_GETEVENTRESPONSE']._serialized_end=624
  _globals['_GETLISTEVENTSREQUEST']._serialized_start=626
  _globals['_GETLISTEVENTSREQUEST']._serialized_end=648
  _globals['_GETLISTEVENTSRESPONSE']._serialized_start=650
  _globals['_GETLISTEVENTSRESPONSE']._serialized_end=712
  _globals['_UPDATEEVENTSTATUSREQUEST']._serialized_start=714
  _globals['_UPDATEEVENTSTATUSREQUEST']._serialized_end=797
  _globals['_LINEPROVIDERSERVICE']._serialized_start=861
  _globals['_LINEPROVIDERSERVICE']._serialized_end=1227
# @@protoc_insertion_point(module_scope)
