# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: line_provider/src/grpc/grpc_api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    "",
    "line_provider/src/grpc/grpc_api.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%line_provider/src/grpc/grpc_api.proto\x12\x0e\x65vent_provider"\x80\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x0c\n\x04odds\x18\x03 \x01(\x01\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x11\n\tfinish_at\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t"I\n\x12\x43reateEventRequest\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0c\n\x04odds\x18\x02 \x01(\x01\x12\x11\n\tfinish_at\x18\x03 \x01(\t";\n\x13\x43reateEventResponse\x12$\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x15.event_provider.Event">\n\x0fGetEventRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x14\n\nevent_name\x18\x02 \x01(\tH\x00\x42\x07\n\x05query"8\n\x10GetEventResponse\x12$\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x15.event_provider.Event"\x16\n\x14GetListEventsRequest">\n\x15GetListEventsResponse\x12%\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x15.event_provider.Event"6\n\x18UpdateEventStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t"A\n\x19UpdateEventStatusResponse\x12$\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x15.event_provider.Event2\x84\x03\n\x13LineProviderService\x12V\n\x0b\x43reateEvent\x12".event_provider.CreateEventRequest\x1a#.event_provider.CreateEventResponse\x12M\n\x08GetEvent\x12\x1f.event_provider.GetEventRequest\x1a .event_provider.GetEventResponse\x12\\\n\rGetListEvents\x12$.event_provider.GetListEventsRequest\x1a%.event_provider.GetListEventsResponse\x12h\n\x11UpdateEventStatus\x12(.event_provider.UpdateEventStatusRequest\x1a).event_provider.UpdateEventStatusResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "line_provider.src.grpc.grpc_api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EVENT"]._serialized_start = 58
    _globals["_EVENT"]._serialized_end = 186
    _globals["_CREATEEVENTREQUEST"]._serialized_start = 188
    _globals["_CREATEEVENTREQUEST"]._serialized_end = 261
    _globals["_CREATEEVENTRESPONSE"]._serialized_start = 263
    _globals["_CREATEEVENTRESPONSE"]._serialized_end = 322
    _globals["_GETEVENTREQUEST"]._serialized_start = 324
    _globals["_GETEVENTREQUEST"]._serialized_end = 386
    _globals["_GETEVENTRESPONSE"]._serialized_start = 388
    _globals["_GETEVENTRESPONSE"]._serialized_end = 444
    _globals["_GETLISTEVENTSREQUEST"]._serialized_start = 446
    _globals["_GETLISTEVENTSREQUEST"]._serialized_end = 468
    _globals["_GETLISTEVENTSRESPONSE"]._serialized_start = 470
    _globals["_GETLISTEVENTSRESPONSE"]._serialized_end = 532
    _globals["_UPDATEEVENTSTATUSREQUEST"]._serialized_start = 534
    _globals["_UPDATEEVENTSTATUSREQUEST"]._serialized_end = 588
    _globals["_UPDATEEVENTSTATUSRESPONSE"]._serialized_start = 590
    _globals["_UPDATEEVENTSTATUSRESPONSE"]._serialized_end = 655
    _globals["_LINEPROVIDERSERVICE"]._serialized_start = 658
    _globals["_LINEPROVIDERSERVICE"]._serialized_end = 1046
# @@protoc_insertion_point(module_scope)
